backend:
  name: github
  repo: ankitkosankar/your-blog-repo
  branch: main

media_folder: "public/uploads"
public_folder: "/uploads"

collections:
  - name: "blogs"
    label: "Blogs"
    folder: "src/content/blogs"
    create: true
    delete: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Image", name: "image", widget: "image" }
      - { label: "Body", name: "body", widget: "markdown" }
